export const environment = {
    urlApi : "https://customermanagement-i1l0.onrender.com/api",
    urlApiUser: 'https://userservice-gh3b.onrender.com',
    rowPanigator : 10,
    ACTIVE: "ACTIVE",
    DISABLE: "DISABLE",
    STA_ACTIVE: "0",
    STA_DISABLE : "1",
    STA_EXAM: '1',
    STA_NOTEXAM: '0',
    DATE_FORMAT: 'yyyy-mm-dd',
    DATE_FORMAT_COMMON: 'yyyy-MM-dd',
    URL_UPLOAD_IMAGE: 'http://localhost:8085/api/upload/images/',
    URL_LOAD_IMAGE: '',
    SRC_IMAGE: '/fe-customermanagement/assets/images/',
    APP_TITLE: 'customermanagement',
    urlApiOAuth : "https://oauthserver-h2s5.onrender.com",
    redirectUri: 'https://hung9605.github.io/fe-customermanagement/oauth2/callback',
    apiNotify: 'wss://userservice-gh3b.onrender.com/ws-notify'
};
