export const environment = {
      urlApi : "http://localhost:8085/api",
      urlApiUser: 'http://localhost:9105',
      urlApiChat: 'http://localhost:9115',
      rowPanigator : 10,
      ACTIVE: "ACTIVE",
      DISABLE: "DISABLE",
      STA_ACTIVE: "0",
      STA_DISABLE : "1",
      STA_EXAM: '1',
      STA_NOTEXAM: '0',
      DATE_FORMAT: 'yyyy-mm-dd',
      DATE_FORMAT_COMMON: 'yyyy-MM-dd',
      URL_UPLOAD_IMAGE: 'http://localhost:8085/api/upload/images/',
      URL_LOAD_IMAGE: '',
      SRC_IMAGE: '/assets/images/',
      APP_TITLE: 'customermanagement',
      urlApiOAuth : "http://localhost:9005",
      redirectUri: 'https://localhost:4200/oauth2/callback',
      apiNotify: 'http://localhost:9115/ws-notify'
  };